<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ShopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('shops')->insert([
            [
                'name' => 'ラーメン二郎',
                'description' => 'ガッツリ系ラーメンのお店',
                'price' => 1000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '海鮮丼の名店',
                'description' => '新鮮な海鮮が楽しめるお店',
                'price' => 2000,
                'open_time' => '10:00:00',
                'close_time' => '21:00:00',
                'category_id' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'しゃぶしゃぶ',
                'description' => 'しゃぶしゃぶのお店',
                'price' => 5000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '西洋',
                'description' => '牛タンシチュー専門店',
                'price' => 3000,
                'open_time' => '12:00:00',
                'close_time' => '23:00:00',
                'category_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ボルティ',
                'description' => 'イタリアンレストラン',
                'price' => 10000,
                'open_time' => '18:00:00',
                'close_time' => '23:00:00',
                'category_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ビストロ',
                'description' => 'フレンチレストラン',
                'price' => 5000,
                'open_time' => '10:00:00',
                'close_time' => '21:00:00',
                'category_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LEON',
                'description' => 'おしゃれなカフェ',
                'price' => 1000,
                'open_time' => '10:00:00',
                'close_time' => '22:00:00',
                'category_id' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '燕',
                'description' => '鍋料理が人気のお店',
                'price' => 15000,
                'open_time' => '18:00:00',
                'close_time' => '23:00:00',
                'category_id' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '華房',
                'description' => '海鮮丼が有名なお店',
                'price' => 5000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '琥珀',
                'description' => '手羽先が有名なお店',
                'price' => 1000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '大',
                'description' => '焼肉専門店',
                'price' => 20000,
                'open_time' => '17:00:00',
                'close_time' => '22:00:00',
                'category_id' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'spice curry',
                'description' => 'インドカレー専門店',
                'price' => 1000,
                'open_time' => '10:00:00',
                'close_time' => '18:00:00',
                'category_id' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '韓',
                'description' => '韓国料理のお店',
                'price' => 2000,
                'open_time' => '17:00:00',
                'close_time' => '23:00:00',
                'category_id' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'テラス',
                'description' => 'ピザ専門店',
                'price' => 3000,
                'open_time' => '12:00:00',
                'close_time' => '22:00:00',
                'category_id' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '喫茶',
                'description' => '昔ながらの喫茶店',
                'price' => 2000,
                'open_time' => '10:00:00',
                'close_time' => '18:00:00',
                'category_id' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '蔵元',
                'description' => '海鮮居酒屋',
                'price' => 10000,
                'open_time' => '19:00:00',
                'close_time' => '22:00:00',
                'category_id' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'favorite',
                'description' => 'パスタが人気なお店',
                'price' => 2000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'park',
                'description' => 'パスタ専門店',
                'price' => 1000,
                'open_time' => '10:00:00',
                'close_time' => '18:00:00',
                'category_id' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'kitchen',
                'description' => 'オムライスが人気のお店',
                'price' => 3000,
                'open_time' => '11:00:00',
                'close_time' => '22:00:00',
                'category_id' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '手羽谷',
                'description' => '手羽先のお店',
                'price' => 1000,
                'open_time' => '09:00:00',
                'close_time' => '18:00:00',
                'category_id' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
